project:
  type: website
title: "Manuals"  
author: "Enrique Miralles"
theme: [journals]

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
      - sidebar:helperspages
      - sidebar:toolspages
  
  
  sidebar:
    - id: helperspages
      title: "Helpers"
      style: "docked"
      background: light
      contents:
        - href: gitHubActions.qmd
          text: Git Hub Actions
        - href: gitRepositorySync.qmd
          text: Git Repository

    - id: toolspages
      title: "Tools"
      contents:
        - href: gitRepositorySync.qmd
          text: Git Repository
        
  page-footer: "Copyright 2024, Enrique Miralles" 
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

extensions:
  - mermaid    


