project:
  type: website

website:
  title: "Manuals"
  navbar:
    left:
      - href: index.qmd
        text: Home
        menu:
          - href: gitHubActions.qmd
            text: Git Hub Actions
          - href: gitRepositorySync.qmd
            text: Git Repository
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



