project:
  type: website

website:
  title: "Manuals"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:helperspages
      - about.qmd

  sidebar:
    - id: helperspages
      title: "Helpers"
      style: "docked"
      background: light
      contents: 
        - href: gitHubActions.qmd
          text: Git Hub Actions
        - href: gitRepositorySync.qmd
          text: Git Repository
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



